### PR TITLE
Add proper pagination support. 

### PR DESCRIPTION
**Pull request by nithinphilips**
This commit adds pagination support introduces in recent versions of Hugo. See https://github.com/spf13/hugo/issues/96

Related to issue #9 

The CSS is from Bootstrap 3 with colors adjusted to match the default lanyon-hugo theme. It may need adjustment.

### CODE REVIEW

**Comment by tummychow** [comment]
Lanyon already provides CSS rules for pagination buttons (as shown in the stub implementation from many moons ago). I would rather see an implementation that uses those, rather than pulling in new CSS rules to support the hugo internal template.

**Comment by ace7** [comment]
@nithinphilips 
Agree with @tummychow , based on your PR, just revert lanyon.css, change *pagination* div in index.html to the following will be fine.
```
<div class="pagination">
  {{ if $paginator.HasNext }}
  <a class="pagination-item older" href="{{ $paginator.Next.URL }}">Older</a>
  {{ else }}
  <span class="pagination-item older">Older</span>
  {{ end }}

  {{ if $paginator.HasPrev }}
  <a class="pagination-item newer" href="{{ $paginator.Prev.URL }}">Newer</a>
  {{ else }}
  <span class="pagination-item newer">Newer</span>
  {{ end }}
</div>
```

**Comment by nithinphilips** [comment]
@tummychow @ace7 Makes sense. Let me rework this.

**Comment by tummychow** [comment]
_ping_ @nithinphilips , just wanted to check if you're still working on this.

**Comment by nithinphilips** [comment]
I've updated the pull request. Reverted changes to `lanyon.css`. Modified `index.html` per @ace7's suggestion.

I tested on a simple site with 21 pages. Hugo created 3 index pages (10 posts max/pg):

**/**

Older     | Newer
------------|----------
/page/2/ |  *Gray*

**/page/2**

Older     | Newer
------------|----------
/page/3/ |  /

**/page/3**

Older     | Newer
------------|----------
*Gray*   | /page/2

**Comment by tummychow** [comment]
:+!: great contribution, thanks!

**Pull request merged**
